--[ Run 'wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS-Alt/main/JWB.OS-WGet-Installer.lua jwbos-installer.lua' to get Installer ]--

print("Installing...")
shell.run("wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS-Alt/main/startup.lua startup.lua")
shell.run("wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS-Alt/main/back.lua back")
shell.run("mkdir os")
shell.run("wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS/main/os/main.lua os/main")
shell.run("wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS-Alt/main/os/files.lua os/files")
shell.run("wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS-Alt/main/os/cmd.lua os/cmd")
shell.run("wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS-Alt/main/os/programs.lua os/programs")
shell.run("wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS-Alt/main/os/chath.lua os/chath")
shell.run("wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS-Alt/main/os/chatj.lua os/chatj")
shell.run("wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS-Alt/main/os/uninstall.lua os/uninstall")
print("Done. Rebooting...")
sleep(2)
os.reboot()
