term.clear()
term.setCursorPos(1,1)
print("JWB.OS")
print("Booting...")
term.setCursorPos(1,4)
sleep(1)
textutils.slowPrint("[][][][][][][][][][]")
sleep(1)
term.setCursorPos(1,6)
print("Complete.")
sleep(1)
print("Auto Updating Updater...")
shell.run("rm os/.uninstall")
shell.run("wget https://github.com/JWBstuhr/JWB.OS/blob/main/os/.uninstall.lua os/.uninstall")
print("Complete.")
print("Starting...")
sleep(2)
shell.run("os/.main")
