term.clear()
term.setCursorPos(1,1)
print("Uninstall (1) or Update (2)?")
print("(Say anything else to Cancel.)")
input = read()
if input == "1" then
 term.clear()
 term.setCursorPos(1,1)
 print("Uninstall JWB.OS?")
 print("(yes/no, y/n)")
 input = read()
 if input == "yes" or input == "y" then
  shell.run("rm back")
  shell.run("rm startup.lua")
  shell.run("rm os/")
  print("Complete. Rebooting.")
  sleep(2)
  os.reboot()
 elseif input == "no" or input == "n" then
  print("Cancelling.")
  sleep(2)
  shell.run(".back")
 else
  print("Not understood, cancelling.")
  sleep(2)
  shell.run(".back")
 end
elseif input == "2" then
 term.clear()
 term.setCursorPos(1,1)
 shell.run("rm back")
 shell.run("rm startup.lua")
 shell.run("rm os/")
 shell.run("pastebin get jM8G1Ziw startup.lua")
 shell.run("mkdir os")
 shell.run("pastebin get 64QDpZss os/main")
 shell.run("pastebin get dV5dpPHr os/files")
 shell.run("pastebin get rsB7r5zP os/cmd")
 shell.run("pastebin get VZW74d4H back")
 shell.run("pastebin get z950PA1G os/uninstall")
 shell.run("pastebin get ptjb3X32 os/programs")
 shell.run("pastebin get HcZjeKVv os/chath")
 shell.run("pastebin get NB5H0QUK os/chatj")
 print("Complete. Rebooting.")
 sleep(2)
 os.reboot()
else
 print("Cancelling...")
 sleep(2)
 shell.run(".back")
end