term.clear()
term.setCursorPos(1,1)
print("Uninstall (1) or Update (2)?")
print("(Say anything else to Cancel.)")
input = read()
if input == "1" then
 term.clear()
 term.setCursorPos(1,1)
 print("Uninstall JWB.OS?")
 print("(yes/no, y/n)")
 input = read()
 if input == "yes" or input == "y" then
  shell.run("rm .back")
  shell.run("rm startup.lua")
  shell.run("rm os/")
  print("Complete. Rebooting.")
  sleep(2)
  os.reboot()
 elseif input == "no" or input == "n" then
  print("Cancelling.")
  sleep(2)
  shell.run("back")
 else
  print("Not understood, cancelling.")
  sleep(2)
  shell.run("back")
 end
elseif input == "2" then
 term.clear()
 term.setCursorPos(1,1)
 shell.run("rm .back")
 shell.run("rm startup.lua")
 shell.run("rm os/")
 shell.run("wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS-Alt/main/startup.lua startup.lua")
 shell.run("wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS-Alt/main/back.lua back")
 shell.run("mkdir os")
 shell.run("wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS-Alt/main/os/main.lua os/main")
 shell.run("wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS-Alt/main/os/files.lua os/files")
 shell.run("wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS-Alt/main/os/cmd.lua os/cmd")
 shell.run("wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS-Alt/main/os/programs.lua os/programs")
 shell.run("wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS-Alt/main/os/chath.lua os/chath")
 shell.run("wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS-Alt/main/os/chatj.lua os/chatj")
 shell.run("wget https://raw.githubusercontent.com/JWBstuhr/JWB.OS-Alt/main/os/uninstall.lua os/uninstall")
 print("Complete. Rebooting.")
 sleep(2)
 os.reboot()
else
 print("Cancelling...")
 sleep(2)
 shell.run("back")
end
